name: my_marketing_pipeline
version: '1.0'
config-version: 2

profile: my_marketing_pipeline

model-paths: ["models"]
macro-paths: ["macros"]

models:
  my_marketing_pipeline:
    staging:
      +materialized: table
    intermediate:
      +materialized: table
    marts:
      +materialized: table
