name: my_marketing_pipeline
version: '1.0'
config-version: 2

profile: my_marketing_pipeline

model-paths: ["models"]
macro-paths: ["macros"]

models:
  my_marketing_pipeline:
    +materialized: table

    staging:
      appsflyer: {}
      attribution: {}

    intermediate:
      appsflyer: {}
      attribution: {}

    marts:
      appsflyer: {}
      attribution: {}
